import type { HomeProvider } from "../types";

export const homeProviders: HomeProvider[] = [
  {
    id: "philips_hue",
    name: "Philips Hue",
    appName: "Hue",
    category: "smart_home",
    logoKey: "philips-hue",
    brandColor: "#f6c343",
    websiteUrl: "https://www.philips-hue.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: true,
    supportsApiToken: false,
    connectionStatus: "beta",
    supportedDeviceTypes: ["Lampen", "Leuchten", "Schalter", "Sensoren"],
    supportedCapabilities: ["power", "brightness", "color", "colorTemperature", "motion"],
    description: "Hue-Geraete koennen spaeter als Lampen, Raeume, Szenen und Garantieobjekte in Avareno landen.",
    userFriendlyLabel: "Licht, Szenen und Hue Bridge"
  },
  {
    id: "smartthings",
    name: "SmartThings",
    appName: "SmartThings",
    category: "bridge",
    logoKey: "smartthings",
    brandColor: "#15a9fd",
    websiteUrl: "https://www.smartthings.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: true,
    supportsOAuth: true,
    supportsApiToken: true,
    connectionStatus: "beta",
    supportedDeviceTypes: ["Bridges", "Lampen", "Steckdosen", "Sensoren", "TVs"],
    supportedCapabilities: ["power", "brightness", "temperature", "humidity", "motion", "contact", "battery"],
    description: "SmartThings kann viele Marken buendeln und ist ein guter erster Cloud-Connector.",
    userFriendlyLabel: "Viele Samsung- und Matter-Geraete"
  },
  {
    id: "tuya_smart_life",
    name: "Tuya / Smart Life",
    appName: "Smart Life",
    category: "smart_home",
    logoKey: "tuya",
    brandColor: "#ff6a00",
    websiteUrl: "https://www.tuya.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: true,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Steckdosen", "Lampen", "Sensoren", "Kameras", "Kleingeraete"],
    supportedCapabilities: ["power", "brightness", "color", "temperature", "humidity", "camera", "energy"],
    description: "Smart-Life-Geraete sollen zuerst sauber erkannt und als Geraetepass gespeichert werden.",
    userFriendlyLabel: "Smart Life App und Tuya-Geraete"
  },
  {
    id: "tp_link_tapo",
    name: "TP-Link Tapo",
    appName: "Tapo",
    category: "smart_home",
    logoKey: "tapo",
    brandColor: "#00bfa5",
    websiteUrl: "https://www.tapo.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "beta",
    supportedDeviceTypes: ["Steckdosen", "Lampen", "Kameras", "Sensoren"],
    supportedCapabilities: ["power", "brightness", "color", "camera", "motion", "energy"],
    description: "Tapo ist fuer viele Haushalte relevant, aber Steuerung bleibt bis zum Adapter klar als geplant markiert.",
    userFriendlyLabel: "Tapo Steckdosen, Lampen und Kameras"
  },
  {
    id: "tp_link_kasa",
    name: "TP-Link Kasa",
    appName: "Kasa Smart",
    category: "smart_home",
    logoKey: "kasa",
    brandColor: "#4bb3fd",
    websiteUrl: "https://www.tp-link.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Steckdosen", "Schalter", "Lampen"],
    supportedCapabilities: ["power", "brightness", "energy"],
    description: "Kasa-Geraete koennen als App-/Provider-Kontext fuer bestehende Steckdosen und Schalter dienen.",
    userFriendlyLabel: "Kasa Smart Produkte"
  },
  {
    id: "shelly",
    name: "Shelly",
    appName: "Shelly Smart Control",
    category: "smart_home",
    logoKey: "shelly",
    brandColor: "#23b9d6",
    websiteUrl: "https://www.shelly.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: true,
    connectionStatus: "beta",
    supportedDeviceTypes: ["Relais", "Schalter", "Steckdosen", "Sensoren"],
    supportedCapabilities: ["power", "energy", "temperature", "humidity", "contact"],
    description: "Shelly ist stark fuer lokale Steuerung und Energie-/Statusdaten.",
    userFriendlyLabel: "Lokale Schalter, Relais und Energie"
  },
  {
    id: "switchbot",
    name: "SwitchBot",
    appName: "SwitchBot",
    category: "smart_home",
    logoKey: "switchbot",
    brandColor: "#e34b4b",
    websiteUrl: "https://www.switch-bot.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: true,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Bots", "Vorhaenge", "Schloesser", "Sensoren", "Hubs"],
    supportedCapabilities: ["power", "lock", "contact", "temperature", "humidity", "battery"],
    description: "SwitchBot-Geraete werden als hilfreiche Alltagsgeraete mit Batterie, App und Support-Schritten modelliert.",
    userFriendlyLabel: "Bots, Vorhaenge, Hubs und Sensoren"
  },
  {
    id: "home_assistant",
    name: "Home Assistant",
    appName: "Home Assistant",
    category: "local_bridge",
    logoKey: "home-assistant",
    brandColor: "#41bdf5",
    websiteUrl: "https://www.home-assistant.io",
    supportsCloud: false,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: true,
    connectionStatus: "beta",
    supportedDeviceTypes: ["Bridge", "Lampen", "Sensoren", "Medien", "Schloesser", "Klima"],
    supportedCapabilities: ["power", "brightness", "color", "temperature", "humidity", "lock", "scene", "mediaPlayback", "battery"],
    description: "Home Assistant bleibt die optionale lokale Power-Bridge fuer Haushalte, die bereits viele Systeme buendeln.",
    userFriendlyLabel: "Lokale Bridge fuer viele Marken"
  },
  {
    id: "matter",
    name: "Matter",
    appName: "Matter",
    category: "local_bridge",
    logoKey: "matter",
    brandColor: "#5b6cff",
    websiteUrl: "https://csa-iot.org/all-solutions/matter/",
    supportsCloud: false,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Matter-Geraete", "Lampen", "Steckdosen", "Sensoren", "Schloesser"],
    supportedCapabilities: ["power", "brightness", "color", "temperature", "lock", "motion", "contact"],
    description: "Matter ist eine zukuenftige lokale Grundlage, aber braucht Controller-/Pairing-Architektur.",
    userFriendlyLabel: "Matter-kompatible Geraete"
  },
  {
    id: "apple_home",
    name: "Apple Home",
    appName: "Home",
    category: "voice_assistant",
    logoKey: "apple-home",
    brandColor: "#8f98a3",
    websiteUrl: "https://www.apple.com/home-app/",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["HomeKit-Geraete", "Matter-Geraete", "Szenen"],
    supportedCapabilities: ["power", "brightness", "color", "lock", "scene", "camera"],
    description: "Apple Home wird als Nutzer-App erkannt; direkte Steuerung braucht spaetere Plattformklaerung.",
    userFriendlyLabel: "Apple Home App und HomeKit"
  },
  {
    id: "google_home",
    name: "Google Home",
    appName: "Google Home",
    category: "voice_assistant",
    logoKey: "google-home",
    brandColor: "#34a853",
    websiteUrl: "https://home.google.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: true,
    supportsOAuth: true,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Nest", "Matter-Geraete", "Lautsprecher", "Displays"],
    supportedCapabilities: ["power", "temperature", "camera", "mediaPlayback", "volume", "presence"],
    description: "Google Home kann spaeter als App-/Oekosystem-Kontext fuer Nest und Matter-Geraete dienen.",
    userFriendlyLabel: "Nest, Speaker, Displays und Matter"
  },
  {
    id: "amazon_alexa",
    name: "Amazon Alexa",
    appName: "Alexa",
    category: "voice_assistant",
    logoKey: "alexa",
    brandColor: "#00a7ce",
    websiteUrl: "https://alexa.amazon.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: true,
    supportsOAuth: true,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Echo", "Matter-Geraete", "Szenen", "Lautsprecher"],
    supportedCapabilities: ["power", "scene", "mediaPlayback", "volume", "presence"],
    description: "Alexa bleibt ein wichtiger App-Kontext, ohne dass Avareno jetzt unsichere Steuerung behauptet.",
    userFriendlyLabel: "Alexa App und Echo-Geraete"
  },
  {
    id: "ikea_home_smart",
    name: "IKEA Home smart",
    appName: "IKEA Home smart",
    category: "smart_home",
    logoKey: "ikea-home",
    brandColor: "#ffcc00",
    websiteUrl: "https://www.ikea.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Lampen", "Rollos", "Luftreiniger", "Schalter"],
    supportedCapabilities: ["power", "brightness", "colorTemperature", "battery", "scene"],
    description: "IKEA-Geraete werden als Haushaltsteile mit App, Anleitung, Garantie und Raumkontext erfasst.",
    userFriendlyLabel: "IKEA Lampen, Rollos und Sensoren"
  },
  {
    id: "fritzbox",
    name: "FRITZ!Box",
    appName: "FRITZ!App Smart Home",
    category: "router",
    logoKey: "fritzbox",
    brandColor: "#d10074",
    websiteUrl: "https://avm.de",
    supportsCloud: false,
    supportsLocal: true,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Router", "Steckdosen", "Thermostate", "DECT-Geraete"],
    supportedCapabilities: ["power", "temperature", "energy", "presence"],
    description: "FRITZ!Box kann spaeter lokale Heimnetz- und DECT-Smart-Home-Signale liefern.",
    userFriendlyLabel: "Router, DECT und Heimnetz"
  },
  {
    id: "sonos",
    name: "Sonos",
    appName: "Sonos",
    category: "media",
    logoKey: "sonos",
    brandColor: "#ffffff",
    websiteUrl: "https://www.sonos.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: false,
    supportsOAuth: true,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Lautsprecher", "Soundbars", "Subwoofer"],
    supportedCapabilities: ["mediaPlayback", "volume", "presence"],
    description: "Sonos-Geraete gehoeren in Avareno zu Medienobjekten mit Anleitung, Kaufnachweis und Raumbezug.",
    userFriendlyLabel: "Lautsprecher und Soundbars"
  },
  {
    id: "roborock",
    name: "Roborock",
    appName: "Roborock",
    category: "cleaning",
    logoKey: "roborock",
    brandColor: "#e43d30",
    websiteUrl: "https://global.roborock.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Saugroboter", "Wischroboter"],
    supportedCapabilities: ["cleaning", "battery"],
    description: "Roborock wird als Care-Geraet mit Wartung, Filterwechseln, Garantie und Reinigungsstatus gedacht.",
    userFriendlyLabel: "Saug- und Wischroboter"
  },
  {
    id: "dyson",
    name: "Dyson",
    appName: "MyDyson",
    category: "appliance",
    logoKey: "dyson",
    brandColor: "#a8ff00",
    websiteUrl: "https://www.dyson.com",
    supportsCloud: true,
    supportsLocal: false,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Luftreiniger", "Ventilatoren", "Staubsauger"],
    supportedCapabilities: ["power", "temperature", "humidity", "battery"],
    description: "Dyson-Produkte sind besonders gute Kandidaten fuer Geraetepass, Filter, Garantie und Support.",
    userFriendlyLabel: "Luftreiniger, Ventilatoren und Pflege"
  },
  {
    id: "eufy",
    name: "Eufy",
    appName: "eufy Security",
    category: "security",
    logoKey: "eufy",
    brandColor: "#2f7cf6",
    websiteUrl: "https://www.eufy.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Kameras", "Tuerklingeln", "Sensoren", "HomeBase"],
    supportedCapabilities: ["camera", "motion", "battery", "alarm"],
    description: "Sicherheitsgeraete werden vor echter Steuerung besonders vorsichtig behandelt.",
    userFriendlyLabel: "Kameras, Klingeln und HomeBase"
  },
  {
    id: "bosch_smart_home",
    name: "Bosch Smart Home",
    appName: "Bosch Smart Home",
    category: "smart_home",
    logoKey: "bosch",
    brandColor: "#e20015",
    websiteUrl: "https://www.bosch-smarthome.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Thermostate", "Sensoren", "Controller", "Alarme"],
    supportedCapabilities: ["temperature", "humidity", "motion", "contact", "alarm", "battery"],
    description: "Bosch Smart Home gehoert in den Home Graph als Care-, Sicherheits- und Raumstatus-System.",
    userFriendlyLabel: "Thermostate, Sensoren und Sicherheit"
  },
  {
    id: "homematic_ip",
    name: "Homematic IP",
    appName: "Homematic IP",
    category: "smart_home",
    logoKey: "homematic-ip",
    brandColor: "#009ee3",
    websiteUrl: "https://homematic-ip.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: false,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Thermostate", "Schalter", "Sensoren", "Aktoren"],
    supportedCapabilities: ["power", "temperature", "humidity", "contact", "battery"],
    description: "Homematic IP ist ein wichtiger deutscher Smart-Home-Kontext fuer Heizung und Sensorik.",
    userFriendlyLabel: "Heizung, Aktoren und Sensoren"
  },
  {
    id: "aqara",
    name: "Aqara",
    appName: "Aqara Home",
    category: "smart_home",
    logoKey: "aqara",
    brandColor: "#ff4d4d",
    websiteUrl: "https://www.aqara.com",
    supportsCloud: true,
    supportsLocal: true,
    supportsMatter: true,
    supportsOAuth: false,
    supportsApiToken: false,
    connectionStatus: "planned",
    supportedDeviceTypes: ["Hubs", "Sensoren", "Schalter", "Kameras", "Schloesser"],
    supportedCapabilities: ["power", "motion", "contact", "temperature", "humidity", "lock", "camera", "battery"],
    description: "Aqara-Geraete koennen ueber Hubs, Matter oder spaetere Provider-Adapter in den Home Graph wachsen.",
    userFriendlyLabel: "Hubs, Sensoren, Schalter und Matter"
  }
];

export function getHomeProviderById(providerId?: string) {
  return homeProviders.find((provider) => provider.id === providerId);
}
