-- Documentation pointer only. Do not paste an older policy draft into the
-- Supabase SQL editor.
--
-- The executable, versioned closed-beta database/RLS source of truth is:
--   supabase/migrations/20260717061246_beta_authorization_rls.sql
--   supabase/migrations/20260717063836_beta_service_role_account_deletion.sql
--
-- Apply migrations through the Supabase CLI and run qa-beta-security.mjs
-- against the intended local/staging project before admitting beta users.
