-- Documentation pointer only. Do not paste an older policy draft into the
-- Supabase SQL editor.
--
-- The executable, versioned closed-beta Storage source of truth is:
--   supabase/migrations/20260717061534_beta_private_storage.sql
--
-- Bucket limits are also defined in supabase/config.toml. Apply migrations
-- through the Supabase CLI and run qa-beta-security.mjs against the intended
-- local/staging project before admitting beta users.
